Rewrite BCn texture utilities in Rust (+ deswizzling)
magcius/noclip.website pull request #445
Opened 2021-08-11 00:52 UTC by Jellonator

PR for first task of #424

2021-08-11 02:30 UTC, magcius requested changes

2021-08-11 02:30 UTC, magcius commented on rust/src/util.rs
> +pub fn get_uint16_be(src: &[u8], offs: usize) -> u16 {
This implementation should work in both configurations. I don't know why we'd ever be on a big-endian target on a website in 2021, and since this version works for both, I'd prefer to just keep this version for everything.

2021-08-11 02:30 UTC, magcius commented on rust/src/util.rs
> +pub fn s3tcblend(a: u8, b: u8) -> u8 {
I don't see a value in sharing this. tbh we should probably use a better approximation for non-GX textures, since what we really want is 1/3 and 2/3 rather than 3/8 and 5/8 (or a fixed-point version that's good enough for the U8 range).

2021-08-11 02:30 UTC, magcius commented on rust/src/bcn_texture.rs
> +#[derive(Copy, Clone, PartialEq, Eq, Debug)]
We don't need all these derives, do we?

2021-08-11 02:30 UTC, magcius commented on rust/src/bcn_texture.rs
> +use wasm_bindgen::prelude::*;
I do not like * imports, please don't use them.

2021-08-11 02:30 UTC, magcius commented on rust/src/bcn_texture.rs
> +pub enum ChannelFormat {
This is really not BCn texture, it's Tegra deswizzling and Tegra decoding. Please rename this to tegra_texture.rs.

2021-08-11 02:30 UTC, magcius commented on rust/src/bcn_texture.rs
> +    color_table[2] = util::expand5to8((color1 & 0x1F) as u8);
I know you moved the color_table[3] = 0xFF; out here for a slight micro-optimization, but unless it makes a significant difference, I would leave it as before.

Note that this representation of a color_table of 16 u8's was optimized for speed in a GC-sensitive tight loop. It's possible that with Rust's compiler and several additional features, we could make this code a lot more ergonomic, first by possibly having a color_table be a length-4 array of four U8's, or an array of U32's instead.

That's not blocking the review though.

2021-08-11 02:30 UTC, magcius commented on src/fres_nx/tegra_texture.ts
> +    case ChannelFormat.Bc1:
Please use switch statements in JS/TS as infrequently as possible.

2021-08-11 02:30 UTC, magcius commented on rust/src/gx_texture.rs
> +        dst[0] = util::expand5to8(((p >> 10) & 0x1F) as u8);
My hope is that expand_n_to_8 would be inlined / constant folded -- I don't see the reason to re-introduce the older expandNto8 functions if we have the generic form.

2021-08-11 02:30 UTC, magcius commented on rust/src/util.rs
> +pub fn halfblend(a: u8, b: u8) -> u8 {
This is not used outside of CMPR. Either we should make the new system use it, or we have no reason to keep it a separate function. I think we should just make CMPR adopt the same expression you added in the generic BC decoders with the cast to u16.

2021-08-11 02:30 UTC, magcius commented on src/fres_nx/tegra_texture.ts
> +export async function decompress_bcn_deswizzle(textureEntry: BRTI, pixels: Uint8Array): Promise<DecodedSurfaceSW> {
Please use `decompress`, the underscore naming scheme is not really that prevalent in the TypeScript code style.

2021-08-11 02:30 UTC, magcius commented on src/fres_nx/tegra_texture.ts
> +    let wasm = await import("../../rust/pkg/index");
Use `const` please.

2021-08-11 02:30 UTC, magcius commented on src/fres_nx/tegra_texture.ts
> +        }
Put `} else {` on one line, please.

2021-08-11 02:30 UTC, magcius commented on rust/src/lib.rs
> +pub use crate::bcn_texture::*;
Please do not use * imports.

2021-08-14 02:44 UTC, Jellonator commented on rust/src/gx_texture.rs
> +        dst[0] = util::expand5to8(((p >> 10) & 0x1F) as u8);
I wasn't sure about this, so I checked the disassembly in Godbolt. You're right, it does get optimized/inlined to the same instructions. I'll keep it as expand_n_to_8 in that case.

2021-08-14 02:47 UTC, Jellonator commented on rust/src/util.rs
> +pub fn halfblend(a: u8, b: u8) -> u8 {
Should the CMPR format use the same 1:2/2:1 color ratio as Tegra?

2021-08-14 02:54 UTC, magcius commented on rust/src/util.rs
> +pub fn halfblend(a: u8, b: u8) -> u8 {
The implementation of halfblend in CMPR is identical to where it's similarly used in the BC1 decoder, it's just extracted to a function in one of them, but not the other.

2021-08-14 02:56 UTC, Jellonator commented on src/fres_nx/tegra_texture.ts
> +export async function decompress_bcn_deswizzle(textureEntry: BRTI, pixels: Uint8Array): Promise<DecodedSurfaceSW> {
The 'decompress' function is also used by Mario Odyssey. I'm gonna test and make sure SMO is fine with this change too.

2021-08-14 02:59 UTC, Jellonator commented on rust/src/util.rs
> +pub fn get_uint16_be(src: &[u8], offs: usize) -> u16 {
I'll remove the versions of the functions that target big endian, but I think it may be best to keep the cfg attributes just in case. I did a quick search before implementing this, and saw that there might be plans for WASM to support big endian devices. Take this with a grain of salt though because I admittedly did not look into it that hard, I might have misread it, or it might have been some kind of translation layer.

2021-08-14 03:06 UTC, magcius commented on rust/src/util.rs
> +pub fn get_uint16_be(src: &[u8], offs: usize) -> u16 {
The implementation `((src[offs] as u16) << 8) | (src[offs+1] as u16)` should work on both little-endian and big-endian systems.

2021-08-14 03:09 UTC, Jellonator commented on rust/src/util.rs
> +pub fn get_uint16_be(src: &[u8], offs: usize) -> u16 {
oh nevermind, I see what you mean. I'll change it to use the non-platform dependent functions then

2021-08-14 03:13 UTC, Jellonator commented
Implemented the sRGB blending as well, based on the formula I found here: https://entropymine.com/imageworsener/srgbformula/

2021-08-14 03:16 UTC, magcius commented
If you want to double-check, official reference for SRGB can be found here:

https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#3.2.3.7%20SRGB%20-%3E%20FLOAT
https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#3.2.3.8%20FLOAT%20-%3E%20SRGB

2021-08-14 03:31 UTC, Jellonator commented on src/fres_nx/tegra_texture.ts
> +export async function decompress_bcn_deswizzle(textureEntry: BRTI, pixels: Uint8Array): Promise<DecodedSurfaceSW> {
SMO textures seem to decompress fine

2021-08-14 18:30 UTC, magcius reviewed
This is looking quite good! A few minor style nits, then this will be good to go.

2021-08-14 18:30 UTC, magcius commented on rust/src/tegra_texture.rs
> +{
I think the proper code style here is same-line braces.

2021-08-14 18:30 UTC, magcius commented on rust/src/util.rs
> +    let v = (a * (weight_a as f32) + b * (weight_b as f32)) / ((weight_a as f32) + (weight_b as f32));
Any reason you're choosing to pass weights as u32's instead of f32's? Is it to prepare for a pure integer version in case we want to avoid float math in the future? If not, I'd prefer to just have this be used like: `blend_srgb_u8(a, b, 1.0f/3.0f, 2.0f/3.0f)`.

2021-08-14 18:30 UTC, magcius commented on rust/src/tegra_texture.rs
> +    const MAX: i8 = 127;
Kinda surprised Rust doesn't have a std::numerical_limits<i8> kinda thing built-in?

2021-08-14 18:30 UTC, magcius commented on rust/src/gx_texture.rs
> +// Use the fast GX approximation.
This comment doesn't quite make as much sense to me, when we're already in the GX implementation.

2021-08-14 18:30 UTC, magcius commented on rust/src/gx_texture.rs
> +    let a = a as u32;
I'm surprised `let a = a` compiles; I figured Rust would warn on shadowing. I kinda don't like shadowing though, so I would prefer if you changed it back to `a_`.

2021-08-14 18:30 UTC, magcius commented on rust/src/gx_texture.rs
> +pub fn s3tcblend(a: u8, b: u8) -> u8 {
No reason for this (and halfblend) to be pub anymore.

2021-08-27 23:16 UTC, merged