Add Unity asset reader + Subnautica scene
magcius/noclip.website pull request #497
Opened 2022-02-17 20:04 UTC by wgreenberg

So far it's just a barebones render of the scanner map, but it's a start!

2022-02-17 20:09 UTC, magcius requested changes

2022-02-17 20:09 UTC, magcius commented on src/Subnautica/scenes.ts
> +    indices: Int32Array,
This should probably be an `interface`, instead of a `class`, and please use semicolons instead of commas.

2022-02-17 20:09 UTC, magcius commented on src/Subnautica/scenes.ts
> +class Vertex {
Mind using `vec3` from gl-matrix instead?

2022-02-17 20:09 UTC, magcius commented on src/Subnautica/scenes.ts
> +class Vertex {
Mind using `vec3` from gl-matrix instead?

2022-02-17 20:09 UTC, magcius commented on src/Subnautica/scenes.ts
> +        }
Could you move this offset into a model matrix UBO? Up to you, but I think that would be helpful going forward.

2022-02-17 20:09 UTC, magcius commented on src/Subnautica/scenes.ts
> +        const renderInst = renderInstManager.newRenderInst();
Consider frustum culling on the AABB bounds?

2022-02-17 20:09 UTC, magcius commented on src/viewer.ts
> +    config.trackResources = false;
Debug change

2022-02-17 20:09 UTC, magcius commented on src/Common/Unity/AssetManager.ts
> +    rangeSize: number,
Please use semicolons, not commas

2022-02-17 20:12 UTC, magcius commented on rust/Cargo.toml
> +debug = true
This change / the -g looks wrong?

2022-02-17 20:19 UTC, wgreenberg commented on rust/Cargo.toml
> +byteorder = "1.4.3"
yeah, it's how i deserialize all the other types -- eventually i could probably replace it w/ the BE/LE functions you've got in util though

2022-02-17 22:00 UTC, wgreenberg commented on src/Subnautica/scenes.ts
> +        const renderInst = renderInstManager.newRenderInst();
honestly not sure how to do this -- would you say it's a must-have, or something that could be implemented later?

2022-02-19 17:58 UTC, magcius reviewed
This is so cool! Finally got it running locally, and it's been fun to mouse around. General note on review:

* As always, authors are given final say on code structure, API designs, and full artistic control for their contributed games, whatever that means ;). Please treat all my nitpicks and suggestions as *optional*, feel free to ignore them, and I will merge this PR without addressing any of them.

* Changes to common/shared code I might hold to a bit higher of a gatekeeping standard. There are two of those changes, really: the change to Geometry.ts (LGTM, harmless), and the Rust Cargo build changes, which I would like to understand a bit more carefully before merging, since it will affect existing games.

* Leak fixes are something that are not required for this PR to be merged, but are required before we make the game public on the site.

2022-02-19 17:58 UTC, magcius commented on src/Subnautica/scenes.ts
> +export const sceneGroup: Viewer.SceneGroup = { id, name, sceneDescs };
Mind adding a `hidden: true` to here? That hides it from the main site, but still makes it visible when in development mode. Means I can merge this PR without having the data fully live yet.

2022-02-19 17:58 UTC, magcius commented on src/Common/Unity/AssetManager.ts
> +    };
Extra semicolon

Also, not a requirement to land, just a reminder that we should probably expose submeshes too. I need to do some investigation to figure out how submeshes map to materials, too.

2022-02-19 17:58 UTC, magcius commented on src/Common/Unity/AssetManager.ts
> +let _wasm: any | null = null;
It would be nice if this wasn't marked as any. You should be able to use an import type now:

```ts
let _wasm: typeof import('../../../rust/pkg/index') | null = null;
```

2022-02-19 17:58 UTC, magcius commented on src/Common/Unity/AssetManager.ts
> +    return new UnityMesh(layout, state, indices.length, mesh.local_aabb);
Reminder that you're leaking the buffers here. If you want to turn on the leak checker, the easiest way to do that is to adjust `loadSceneDelta` from 1 to 0 in `main.ts`.

Maybe I should do that by default in development builds....

2022-02-19 17:58 UTC, magcius commented on src/Common/Unity/AssetManager.ts
> +    ], { buffer: makeStaticDataBuffer(device, GfxBufferUsage.Index, indices), byteOffset: 0 });
Again, reminder that you're leaking the buffers here.

2022-02-19 17:58 UTC, magcius commented on rust/src/unity/mesh.rs
> +        reader.set_endianness(asset.header.endianness);
There's a part of me that believes we shouldn't see anything but little-endian in TYOOL2022 -- and I believe the new uncompressed mesh loading code relies on that. PowerPC is dead :pray:, we can give it up now. So we could probably turn this into an error / assert.

2022-02-19 17:58 UTC, magcius commented on rust/src/unity/mesh.rs
> +        }
Optional feedback, not required for merge:

I think it might be unclear that this is doing work to uncompress mesh data. I wonder if we should have an "unpack_mesh_data(channel_mask)" method that unpacks to a sequence of streams/channels, and then the TS code doesn't have to care about whether the data is compressed or not, it can just iterate over the final stream/channel setup.

For a compressed mesh, we'd have a stream per channel (e.g. a stream for positions, a stream for UVs, a stream for normals, etc.), while we'd continue to use the packed data on the Unity side.

2022-02-19 17:58 UTC, magcius commented on rust/Cargo.toml
> +wasm-opt = ['-Os', '--debuginfo']
I'm still a bit scared about putting this into the final build; is there a way to only put this in webpack.dev.js mode?

2022-02-19 17:58 UTC, magcius commented on src/Common/Unity/AssetManager.ts
> +        _wasm = await import('../../../rust/pkg/index');
It would also be great if the Rust package had namespaces, since just having a type called "AssetInfo" in the Rust code is a bit confusing, and if we do textures, we might run into conflicts with the GX texture loader code, but I think that's a taller order...

luv u 2 wasm-bindgen

2022-02-19 22:52 UTC, wgreenberg commented on src/Common/Unity/AssetManager.ts
> +export const a_Normal = 1;
ohh channel indices make way more sense!

2022-02-19 23:03 UTC, wgreenberg commented on rust/src/unity/mesh.rs
> +        reader.set_endianness(asset.header.endianness);
funny enough, all unity asset files start out as big endian, and then switch endianness based on a value read in the header

2022-02-19 23:19 UTC, magcius commented on rust/src/unity/mesh.rs
> +        reader.set_endianness(asset.header.endianness);
I can imagine a big-endian header, but I would hope most of the actual these days past the header is little endian.

2022-02-19 23:20 UTC, wgreenberg commented on rust/src/unity/mesh.rs
> +        }
this sounds good to me, though i don't have a good idea of how to implement that yet. how about for now, i rename these to `unpack_*`?

2022-02-19 23:25 UTC, magcius commented on rust/src/unity/mesh.rs
> +        }
As I mentioned, all suggestions are 100% optional. Feel free to rename, or simply not do anything!

2022-02-19 23:39 UTC, wgreenberg commented on rust/Cargo.toml
> +wasm-opt = ['-Os', '--debuginfo']
stuck this in a dev-build-only config!

2022-02-19 23:39 UTC, wgreenberg commented on src/Common/Unity/AssetManager.ts
> +    ], { buffer: makeStaticDataBuffer(device, GfxBufferUsage.Index, indices), byteOffset: 0 });
fix'd

2022-02-19 23:40 UTC, wgreenberg commented on src/Common/Unity/AssetManager.ts
> +        _wasm = await import('../../../rust/pkg/index');
yeahhh, maybe in future work i'll just rename everything `Unity*`

2022-02-19 23:59 UTC, merged