Basic JPAC2-11 Support
magcius/noclip.website pull request #569
Opened 2023-01-30 23:32 UTC by elijah-thomas774

As title says, basics support for JPAC2-11 (used by Skyward Sword). 
This still contains  a bug that stalls on a small amount of resources (only a few) (around the 1600 or 1700 index into skyward swords particle file). This however makes it so most effects can be viewed as the format is still largely identical to JPAC2-10.

2023-03-22 02:01 UTC, magcius commented
Hi, sorry for taking so long to get around to this. Given the similarity between JPAC2-10 and JPAC2-11, it might make sense to just handle it in `parseResource_JPAC2_10` -- make it accept a version parameter, and just adjust the parsing code for the handful of changed blocks depending on the version. I pushed a flag cleanup in 8aca3a867ff68e449da95e2cedc73149b4c37856 which should hopefully make it easier to understand and modify.

2023-06-02 21:24 UTC, elijah-thomas774 commented
Ive updated it with the flag cleanup, the status of how well it works is still the same prior

2023-07-18 06:36 UTC, magcius requested changes
Sorry for the late review on this, I've been fairly busy.

2023-07-18 06:36 UTC, magcius commented on src/Common/JSYSTEM/JPA.ts
> +function parseResource_JPAC2_10(res: JPAResourceRaw, version: number): JPAResource {
```ts
function parseResource_JPAC2_10(res: JPAResourceRaw, version: JPACVersion.JPAC2_10 | JPACVersion.JPAC2_11) {

2023-07-18 06:36 UTC, magcius commented on src/Common/JSYSTEM/JPA.ts
> +            if (!isJPAC2_11) // JPAC2_10
Please obey existing formatting -- braces on same line. This should also be `if (version === JPACVersion.JPAC2_10)` now.

2023-07-18 06:36 UTC, magcius commented on src/Common/JSYSTEM/JPA.ts
> +            const indTextureID = view.getUint8(tableIdx + (!isJPAC2_11 ? 0x25 : 0x4E));
Is this a TODO or not?

2023-07-18 06:36 UTC, magcius commented on src/Common/JSYSTEM/JPA.ts
> +        return parseResource_JPAC2_10(resRaw, 11);
```ts
else if (version === JPACVersion.JPAC2_10 || version === JPACVersion.JPAC2_11)
    return parseResource_JPAC2_10(resRaw, version);
```

2024-03-02 22:17 UTC, closed without merging