Wow portal fixeroo
magcius/noclip.website pull request #674
Opened 2024-05-11 21:37 UTC by wgreenberg

Fixes #643 and makes portal culling much more effective in general.

2024-05-11 21:49 UTC, magcius requested changes

2024-05-11 21:49 UTC, magcius commented on src/Geometry.ts
> +        this.far = new Plane();
Why are the near/far planes divorced from the others? Just make them part of the plane array

2024-05-11 21:49 UTC, magcius commented on src/Geometry.ts
> +    constructor(nPlanes: number) {
Mind defaulting this?

```suggestion
    constructor(nPlanes = 6) {
```

2024-05-11 21:49 UTC, magcius commented on src/Geometry.ts
> +        }
```suggestion
        while (this.planes.length < o.planes.length)
            this.planes.push(new Plane());
```

2024-05-11 21:49 UTC, magcius commented on src/Geometry.ts
> +        this.planes[2].set4Unnormalized(-(m[3] - m[0]), -(m[7] - m[4]), -(m[11] - m[8]) , -(m[15] - m[12])); // Right
Were these switched for any reason?

2024-05-12 19:12 UTC, wgreenberg commented on src/Geometry.ts
> +        this.far = new Plane();
ah yeah, these were from when i was creating a new frustum and copying over the near/far planes. they can be folded in

2024-05-12 19:18 UTC, wgreenberg commented on src/Geometry.ts
> +        this.planes[2].set4Unnormalized(-(m[3] - m[0]), -(m[7] - m[4]), -(m[11] - m[8]) , -(m[15] - m[12])); // Right
ah yeah, my frustum viewer debug code needed the planes to be in "rotational" order

2024-05-13 03:17 UTC, merged