Cutscene (demo) support for Wind Waker
magcius/noclip.website pull request #717
Opened 2024-11-13 20:11 UTC by themikelester

https://github.com/user-attachments/assets/af4ff791-d84e-4e4e-8ae5-221e3319b8fe

https://github.com/user-attachments/assets/bff512f2-c8cf-435a-97a3-496101d63ad1

<img width="797" alt="Screenshot 2024-11-13 at 9 34 14 AM" src="https://github.com/user-attachments/assets/8e3cbc8a-6dc9-4b14-8304-bc2ee4c47c15">

- Added JStudio to JSystem. Most camera and actor functionality is supported. Messages, Lights, and Fog unimplemented.
- Added all JStudio cutscene events from Wind Waker. This includes room, layer, and position info. Most are playable.
- New "Cutscenes" UI element when in a Scene which has at least one demo (pictured above).   
- Added new "Title Screen" Scene which has the playable title screen demo.
- Pausing during a demo allows noclip-style FPS camera. Resuming will snap back to the demo camera.

- Moved `globals.roomStatus`  into new `globals.roomCtrl`, along with `demoArcName`. This is closer to the game's structure and I suspect will make things easier in the future. 
- Moved Aryll (d_a_npc_ls1) out of LegacyActors. She now responds to demo events (e.g. see Awaken on Outset)

2024-11-16 18:01 UTC, magcius requested changes
Apologies for the delay here, I was away from any computers for the entire previous week.

There's a lot of code here to go through and look at. Most of it looks reasonable, but I just need to make sure I can work on it in the future, since Wind Waker is a game I do fix up frequently.

In general, there's a lot of cases where you don't follow the existing conventions of the noclip codebase. I don't care too deeply about it, since it's stuff we can fix after merge, but I would like you to fix it. I've only flagged the first "infraction" of each type I saw, but please review the patch and make sure it's addressed everywhere.

There's also a question about how to expose this to users. Since certain cutscenes might be broken, actors might be missing, etc., I think the best way forward for this would be to remove the Cutscenes panel and just expose each individual scene as an entry in the toplevel Scenes panel. That way we can roll them out as they achieve parity, and we don't complicate the UI.

I think eventually it might make sense to tie this into the Studio mode UI so you can rewind / time skip around, but that's only a nebulous idea in my head and might not actually make sense.

2024-11-16 18:01 UTC, magcius commented on src/ZeldaWindWaker/Main.ts
> +        }
If you had saved the InputManager from the SceneContext, then you could also set `isMouseEnabled = false;` which disables all camera inputs, and removes the dragging hand cursor as well.

2024-11-17 14:34 UTC, themikelester commented on src/Common/JSYSTEM/JStudio.ts
> +    private mValue: number;
I agree. I meant to fix these up (this is mostly coming from the decomp convention), but some got left behind. I'll clean everything up...

2024-11-18 02:30 UTC, themikelester commented on src/Common/JSYSTEM/JStudio.ts
> +    getValue() { return this.mValue; }
My bad, I know you prefer `public` on member functions, I just got lazy. Fixed!

2024-11-18 02:41 UTC, themikelester commented on src/Common/JSYSTEM/JStudio.ts
> +    private mUpdateFunc?: (varval: TVariableValue, x: number) => void;
I like it. Better for debugging because the objects just aren't missing fields. I've fixed em all up.

2024-11-18 02:41 UTC, themikelester commented on src/Common/JSYSTEM/JStudio.ts
> +function dataOpToString(enumValue: EDataOp) {
Wow! I googled around for that for a good 15 minutes and figured it wasn't possible. This is great to know.

2024-11-18 03:01 UTC, themikelester commented on src/Common/JSYSTEM/JStudio.ts
> +            }
Ah, it happens in `obj.prepare()`. Basically we're just parsing the block header here in order to create the write object, and then the meat happens in that object's `prepare()`, including moving to the next function. A bit goofy, but it's what they did and I figured I'd keep it until this was totally done, then maybe come back and simplify all this parsing code.

2024-11-18 03:02 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        // removeTexNoAnimator(this.morf.model, this.btpAnim.anm);
Ah, makes some sense, thanks! Removed.

2024-11-18 03:05 UTC, themikelester commented on src/ZeldaWindWaker/d_kankyo_wether.ts
> +    const fili = globals.roomCtrl.status[globals.mStayNo].data.fili;
Is it time to start a `d_com_inf_game.ts`??

2024-11-18 03:11 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +        })(); });
Ha yea I know what you mean. But you should have seen what I had before 😂. The only issue is that actors need to be available to `fopAcM_searchFromName()` at demo parse time (same frame the demo is started) so that the demo can grab them for later writing. We could probably have that function search the `ct` queue, I bet that would work just fine. You may see some actors pop in, but that might be preferable to this.

2024-11-18 03:13 UTC, themikelester commented on src/ZeldaWindWaker/d_resorce.ts
> +        resID &= 0x0000FFFF; // Consider resID as a short
Actually no, and this took me a minute to figure out. The game has several layers of `Get*Res*()` and starting from here it masks to a short. JStudio actually has a few places where it passes in a u32 with some higher bits set, and relies on this function to ignore them. 

I could have done the masking in those functions, but I figured it would be safer and easier to do the mask here in case other functions in the future require the same behavior.

2024-11-18 03:18 UTC, themikelester commented on src/ZeldaWindWaker/m_do_ext.ts
> +        if (this.prevMorf < 0.0 || morfFrames <= 0.0) {
Oh it was causing issues with the npc animation. The original game logic is `<=` here, and Aryll relies on `morfFrames = 0.0` to be accepted by this `if`.

https://github.com/zeldaret/tww/blob/b6d037364470128eec6f88111fc9768833db7f7c/src/m_Do/m_Do_ext.cpp#L1333

2024-11-18 03:19 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +        globals.roomCtrl.demoArcName = undefined;
The game actually does this during scene creation, but I'm with you on that. I think I'd better leave that to you though, there's still a lot within `globals` that I'm unfamiliar with.

2024-11-18 03:20 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +    new SceneDesc("sea_T", "Title Screen", [44]),
Only if you want it to autoplay. As it is now, that cutscene UI will appear and you can select the Title Screen cutscene to play it.

2024-11-18 03:25 UTC, themikelester commented on src/ZeldaWindWaker/SComponent.ts
> +    return deg * 182.04445;
Ah, I should have spotted that. OK I've renamed `cM__Deg2Short` to `cM_deg2s` (so that it's easier to compare with the decomp). I only had to change one use case. I left the rest as they're named now. I hope that's what you had in mind.

2024-11-18 03:37 UTC, themikelester commented
>  I think the best way forward for this would be to remove the Cutscenes panel and just expose each individual scene as an entry in the toplevel Scenes panel. That way we can roll them out as they achieve parity, and we don't complicate the UI.

I'm totally down with this. I actually waffled between these two styles. I'll make this change.

2024-11-18 03:37 UTC, themikelester commented
> I think eventually it might make sense to tie this into the Studio mode UI so you can rewind / time skip around, but that's only a nebulous idea in my head and might not actually make sense.

Yep, my thoughts exactly! I'll get the basics in and then we can go from there.

2024-11-18 04:22 UTC, themikelester commented on src/Common/JSYSTEM/JStudio.ts
> +class DataVal {
This is super neat! Ended up being much cleaner, and type safer. Although still a little funkiness in the Immediate/Time case where you need both a float and int to be available. But I'm much happier with this way.

2024-11-21 04:46 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +        }
Done!

2024-11-21 04:49 UTC, themikelester commented
@magcius I'm happy with this. Anything else you think is worth changing before merging?

2024-11-21 05:04 UTC, magcius reviewed
I apparently forgot to hit publish a few days ago.

2024-11-21 14:25 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +        if (globals.scnPlay.demo.getMode() == EDemoMode.Ended) {
Well spotted. That's a copy/paste error.

2024-11-21 14:28 UTC, merged