Link now appears in cutscenes (Neat!!)
magcius/noclip.website pull request #732
Opened 2024-11-29 00:35 UTC by themikelester

<img width="856" alt="Screenshot 2024-11-28 at 5 00 01 PM" src="https://github.com/user-attachments/assets/11b12e7b-dc79-425f-b49f-3a2ef34b1c81">
<img width="852" alt="Screenshot 2024-11-28 at 5 01 47 PM" src="https://github.com/user-attachments/assets/1ce1d5e2-da94-4bba-9298-6eeecb5029df">

This is a pretty straightforward actor implementation in d_a.ts, but I wanted to put it up as a PR because it'll require uploading a new `extra.crg1_arc` because of Link's animation table. 

Most of the functionality is there, still a few things to clean up. Item equipping (mostly the sword), pupil animation, etc.

2024-12-03 05:08 UTC, magcius requested changes

2024-12-03 05:08 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +        //        layer. Is there something wrong with noclip's translucency handling?
The default mDoExt_modelEntryDL draws opaque shapes to drawListSet[0], and translucent shapes to drawListSet[1]. The only thing that says that one is after the other is the code that draws the lists in Main.ts. A GfxRenderInstList is sort of equivalent to a J3DDrawBuffer.

I'm guessing the original game has some very specific handling for this in the draw function that would take some work to replicate in noclip. My Link actor hacks were done on the quick for video work.

2024-12-03 05:08 UTC, magcius commented on src/ZeldaWindWaker/Main.ts
> +            fopAcM_create(globals.frameworkGlobals, dProcName_e.d_a_py_lk, 0, [-25414,3501,219], globals.mStayNo, null, null, 0xFF, -1);
Where does this come from and why? Seems wrong.

2024-12-03 05:08 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +    private gdnChk = new dBgS_GndChk()
gdnChk? Is that a typo?

2024-12-03 05:08 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +        if (this.proc) this.proc(globals);
I'm surprised this passes the correct this object. In general you would need a call/apply, bind on set, or use arrow functions for the definitions of proc methods. See the modeProcInit/modeProcExec helpers I have for this.

2024-12-03 05:08 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +        const anmDataView = globals.findExtraSymbolData(`d_a_player_main.o`, `mAnmDataTable__9daPy_lk_c`).createDataView();
I wouldn't be opposed if you just embedded this table directly into the actor source code.

2024-12-05 03:21 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +            fopAcM_create(globals.frameworkGlobals, dProcName_e.d_a_py_lk, 0, [-25414,3501,219], globals.mStayNo, null, null, 0xFF, -1);
Good catch, the position is a leftover (it's his position on Outset during the title cutscene, but it depends on that demos offset). I'll just spawn him at the origin...

2024-12-05 03:24 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +    private gdnChk = new dBgS_GndChk()
You've never head of a grouden check?! Good catch 😅

2024-12-05 03:28 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        if (this.proc) this.proc(globals);
Hmm I'm surprised it works too. I thought I would have called `.bind()` when I set the proc, but I must have slipped it. I'll check out `modeProcInit`...

2024-12-05 03:32 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        const anmDataView = globals.findExtraSymbolData(`d_a_player_main.o`, `mAnmDataTable__9daPy_lk_c`).createDataView();
I started that way, but I think I'm going to be adding more animations soon and the data for each is 5 properties so it gets verbose quickly. Plus its fun to be able to call any Link anim by name just to try em all out. 

I'll leave it up to you.

2024-12-05 03:39 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        //        layer. Is there something wrong with noclip's translucency handling?
Ah I see, that's very clear. I've modified the comment.

2024-12-05 04:12 UTC, magcius commented on src/ZeldaWindWaker/Main.ts
> +            fopAcM_create(globals.frameworkGlobals, dProcName_e.d_a_py_lk, 0, [-25414,3501,219], globals.mStayNo, null, null, 0xFF, -1);
Won't this spawn Link on all maps, including those without cutscenes or Link in those cutscenes? I'd prefer if the Link actor was spawned when a cutscene is started, if possible.

2024-12-05 05:46 UTC, magcius requested changes

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/Main.ts
> +        }
As mentioned before, I don't want a Link spawning in every map. Spawn it in the cutscene system if you must.

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/Main.ts
> +
Can you load these in the Link actor? I'm not sure why this is necessary here.

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +            const slopeGrade = Math.sqrt(norm[0] * norm[0] + norm[2] * norm[2]);
```suggestion
            const slopeGrade = Math.hypot(norm[0], norm[2]);
```

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +                this.anmBtp.frameCtrl.currentTimeInFrames = anmFrame;
```suggestion
                this.anmBck.setFrame(anmFrame);
                this.anmBtp.setFrame(anmFrame);
```

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +            this.anmBck.frameCtrl.currentTimeInFrames = anmFrame;
```suggestion
            this.anmBck.setFrame(anmFrame);
```

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +        if (this.demoMode != 5) {
```suggestion
        if (this.demoMode !== LinkDemoMode.WaitTurn) {
```

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +        this.vel[1] = moveVel * Math.cos(cM_s2rad(this.rot[1]));
Should this not be `this.vel[2]`? Y axis is usually up.

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +        const handRJointMtx = this.model.shapeInstanceState.jointToWorldMatrixArray[0x0D];
Sometimes you have constants for these or search by name, other times you don't?

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +        if (this.curMode == d_a_py_lk_mode.tool) {
Please remember to use `===` and `!==` for comparisons in TypeScript. This goes for every comparison in this PR.

2024-12-05 05:46 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +enum LkAnim {
If you are not using the stringification feature of enums, please mark them as `const enum`.

2024-12-07 03:48 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +        }
Ah that is what's happening now. This code only runs in the demo scenes (not regular scenes), all of which require that the Link actor be spawned before the demo is started.

2024-12-07 03:51 UTC, themikelester commented on src/ZeldaWindWaker/Main.ts
> +
Yes, totally. I think that's a better place.

2024-12-07 04:01 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +            const slopeGrade = Math.sqrt(norm[0] * norm[0] + norm[2] * norm[2]);
Good to know!

2024-12-07 04:05 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +                this.anmBtp.frameCtrl.currentTimeInFrames = anmFrame;
Fixed

2024-12-07 04:06 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        if (this.demoMode != 5) {
Fixed

2024-12-07 04:10 UTC, magcius commented on src/ZeldaWindWaker/d_a.ts
> +                this.anmBtp.frameCtrl.currentTimeInFrames = anmFrame;
hm, I thought mDoExt_baseAnm had getFrame/setFrame on them directly, but that's just a TP feature. We should probably add those as well.

2024-12-07 04:11 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        this.vel[1] = moveVel * Math.cos(cM_s2rad(this.rot[1]));
Wow! Good catch. This code is currently only used for a small part of one demo (at least in the set of demos that I've been iterating on) so I hadn't noticed. But it does fix his positioning in that scene.

2024-12-07 04:12 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +enum LkAnim {
Right! That's a good reminder.

2024-12-07 04:13 UTC, magcius commented on src/ZeldaWindWaker/Main.ts
> +        }
Ah, I missed that this was in DemoDesc.

2024-12-07 06:29 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        if (this.curMode == d_a_py_lk_mode.tool) {
Fixed!

2024-12-07 06:29 UTC, themikelester commented on src/ZeldaWindWaker/d_a.ts
> +        const handRJointMtx = this.model.shapeInstanceState.jointToWorldMatrixArray[0x0D];
Went ahead and just made an LkJoint enum (filled only with the ones currently used). I think it's clearer this way.

2024-12-07 21:30 UTC, magcius approved these changes

2024-12-07 21:31 UTC, merged