J2D: Implement JSystem 2D rendering library, use it display Wind Waker place names
magcius/noclip.website pull request #735
Opened 2024-12-12 14:40 UTC by themikelester

<img width="1123" alt="Screenshot 2024-12-12 at 4 28 38 PM" src="https://github.com/user-attachments/assets/c344302b-f8e7-4639-93f6-e453b5b6e9d1" />

- Added `src/Common/JSYSTEM/J2D.ts`
- Added new automatic file type handling, `BLO` (Binary Layout). 
- Added `fopMsgM` functionality to `framework.ts`
- Implemented place names handing in `src/ZeldaWindWaker/d_place_name.ts`

BLO files contain layout data for 2D elements. It is made up of a hierarchy of J2DPanes (essentially just a bounding box) and J2Pictures. Child elements inherit the transform from their parents. The entire hierarchy contained in a single root J2DScreen object. I followed the pattern of J3D and split up the loading functions from the runtime objects. 

J2D and BLO files can also be used to render message boxes during demos. I'm hoping that others will find uses for them as well. 

As for place names: currently, the only ones that will display are Outset Island and The Forsaken Fortress during their intro cutscenes.

2024-12-13 04:20 UTC, magcius commented on src/Common/JSYSTEM/J2D.ts
> +import ArrayBufferSlice from "../../ArrayBufferSlice.js";
Something worth noting is that J2D has two versions. The version in Wind Waker is v1. v2 is found in Twilight Princess (and possibly other games like Pikmin 2?)

So you might you want to rename this to J2Dv1.ts or something.

2024-12-13 04:20 UTC, magcius commented on src/Common/JSYSTEM/J2D.ts
> +    public drawSelf(renderInstManager: GfxRenderInstManager, viewerRenderInput: ViewerRenderInput, ctx2D: J2DGrafContext, offsetX: number, offsetY: number) { }
Should this be abstract?

2024-12-13 04:20 UTC, magcius commented on src/Common/JSYSTEM/J2D.ts
> +        // @NOTE: The y axis is inverted by this ortho matrix. Gamecube origin is top-left, ours is bottom left.
This seems wrong? The clip space should be the same between both GameCube and noclip, with 0, 0 being the bottom left. The viewport space is different, but that's not involved here.

2024-12-13 04:20 UTC, magcius commented on src/Common/JSYSTEM/J2D.ts
> +        // @NOTE: Y positions are inverted, to account for the projection matrix Y-flip. Gamecube origin is top-left, ours is bottom left.
Again, this seems sketchy.

2024-12-13 04:20 UTC, magcius commented on src/ZeldaWindWaker/d_place_name.ts
> +export function updatePlaceName(globals: dGlobals) {
Could you namespace this, like, `dPn__update()`?

2024-12-13 04:20 UTC, magcius commented on src/Common/JSYSTEM/J2D.ts
> +    private tex: BTIData;
```suggestion
    private tex: BTIData | null = null;
```

2024-12-15 15:42 UTC, themikelester commented on src/Common/JSYSTEM/J2D.ts
> +import ArrayBufferSlice from "../../ArrayBufferSlice.js";
Oo that's good to know. I'm down with that plan, I'll rename...

2024-12-15 15:46 UTC, themikelester commented on src/Common/JSYSTEM/J2D.ts
> +    public drawSelf(renderInstManager: GfxRenderInstManager, viewerRenderInput: ViewerRenderInput, ctx2D: J2DGrafContext, offsetX: number, offsetY: number) { }
I don't think so, because the J2DPane can't be abstract. I've added to that comment to make it a bit more clear though.

2024-12-15 15:47 UTC, themikelester commented on src/Common/JSYSTEM/J2D.ts
> +        // @NOTE: The y axis is inverted by this ortho matrix. Gamecube origin is top-left, ours is bottom left.
Hmm, I'll look more into this...

2024-12-15 15:48 UTC, themikelester commented on src/ZeldaWindWaker/d_place_name.ts
> +export function updatePlaceName(globals: dGlobals) {
Oh I'd seen that pattern around and wondered about it, now it makes sense. Yes I'll follow that pattern.

2024-12-15 16:12 UTC, themikelester commented on src/Common/JSYSTEM/J2D.ts
> +        // @NOTE: The y axis is inverted by this ortho matrix. Gamecube origin is top-left, ours is bottom left.
OK after double checking, it _does_ seem like J2D has its origin in the top left. Here's the relevant data from the J2DPicture which controls the positioning for the Wind Waker place name:
```
{
  basePos: 0
  h: 40
  w: 360
  x: 38
  y: 66
}
```

And a screenshot from the original game:
<img width="785" alt="Screenshot 2024-12-15 at 6 04 44 PM" src="https://github.com/user-attachments/assets/1eb68c81-df29-4a46-88de-eeba3fd53b68" />

A basePos of 0 doesn't manipulate the origin or the coordinate system at all. I also check that the one parent of the pane doesn't do anything to manipulate the coordinate system. 

I could always adjust this later once we have more use cases for J2D. It should become obvious very fast if this coordinate system is wrong.

2024-12-16 04:55 UTC, magcius commented on src/Common/JSYSTEM/J2D.ts
> +        // @NOTE: The y axis is inverted by this ortho matrix. Gamecube origin is top-left, ours is bottom left.
Right, so this is working because when J2D creates the orthographic matrix, it calls C_MTXOrtho like this:

https://github.com/zeldaret/tww/blob/ced4f69ee7af0d6d2e5c60d925bce3854954d86a/src/JSystem/J2DGraph/J2DOrthoGraph.cpp#L27

The arguments to C_MTXOrtho are top, bottom, left, right. So this is putting the top at the origin Y, and the bottom at the size's Y. It has nothing to do with the GameCube's clip space, it's just how J2DOrthoGraph chooses to set up its coordinate system, which the projection matrix will then map to the typical clip space unit cube, which is the same between GameCube and noclip*.

Note that noclip's projectionMatrixForCuboid takes the arguments in a different order, it uses left, right, bottom, top (which matches the glOrtho convention).

* Note that GameCube and noclip differ in clip-space along Z (GameCube uses the unconventional -1...0, and noclip either uses 0...1 or -1..1 depending on backend and availability of the EXT_clip_control extension). But that doesn't concern you here; for X and Y they're identical.

2024-12-16 17:48 UTC, magcius requested changes

2024-12-16 17:48 UTC, magcius commented on src/Common/JSYSTEM/J2Dv1.ts
> +    private static defaultCtx: J2DGrafContext;
Please do not use module-scope or static variables in noclip code if they hold onto other objects. They will outlive the scene, and will be kept in memory even if the user switches to another game. Pass things through, always.

2024-12-17 17:55 UTC, themikelester commented on src/Common/JSYSTEM/J2Dv1.ts
> +    private static defaultCtx: J2DGrafContext;
Oo right, and you've told me that before. My bad! And a good reminder for the reasoning. I'll fix this up...

2024-12-17 18:00 UTC, magcius approved these changes

2024-12-17 18:00 UTC, merged